[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 5

[theme]
primaryColor = "#388BFD"
backgroundColor = "#0D1117"
secondaryBackgroundColor = "#161B22"
textColor = "#E6EDF3"
font = "sans serif"

[browser]
gatherUsageStats = false

[runner]
fastReruns = true
